[theme]
primaryColor = "#D8272E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#BFBFBF"
textColor = "#333333"
font = "sans serif"
base="light"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true
